// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: nevermore

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Chart;
lv_obj_t * ui_Panel0;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_PressureIn;
lv_obj_t * ui_HumidityIn;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_PressureOut;
lv_obj_t * ui_HumidityOut;
lv_obj_t * ui_VocPanel;
lv_obj_t * ui_VocBarLine100;
lv_obj_t * ui_VocBars;
lv_obj_t * ui_VocBarIn;
lv_obj_t * ui_VocLabelIn;
lv_obj_t * ui_VocValueIn;
lv_obj_t * ui_VocBarOut;
lv_obj_t * ui_VocLabelOut;
lv_obj_t * ui_VocValueOut;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
