// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: nevermore

#ifndef _NEVERMORE_UI_H
#define _NEVERMORE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Panel0;
extern lv_obj_t * ui_PressureLabels;
extern lv_obj_t * ui_PressureIn;
extern lv_obj_t * ui_PressureOut;
extern lv_obj_t * ui_HumidityLabels;
extern lv_obj_t * ui_HumidityIn;
extern lv_obj_t * ui_HumidityOut;
extern lv_obj_t * ui_ChartBox;
extern lv_obj_t * ui_ChartOverlay;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_ChartLabels;
extern lv_obj_t * ui_VocLabels;
extern lv_obj_t * ui_VocIn;
extern lv_obj_t * ui_VocOut;
extern lv_obj_t * ui_TempLabels;
extern lv_obj_t * ui_TempIn;
extern lv_obj_t * ui_TempOut;
extern lv_obj_t * ui_ChartMax;
extern lv_obj_t * ui_XAxisScale;
extern lv_obj_t * ui_FanBox;
extern lv_obj_t * ui_FanPowerText;
extern lv_obj_t * ui_FanPower;
extern lv_obj_t * ui_FanPowerArc;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
