// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: circle-240

#include "ui/common.h"

#define ui_no_plot (ui.screen)
#define ui_TempIn2 (ui.temp_in)
#define ui_TempOut2 (ui.temp_out)
#define ui_HumidityIn2 (ui.humidity_in)
#define ui_HumidityOut2 (ui.humidity_out)
#define ui_PressureIn2 (ui.pressure_in)
#define ui_PressureOut2 (ui.pressure_out)
#define ui_VocIn2 (ui.voc_in)
#define ui_VocOut2 (ui.voc_out)
#define ui_FanPower2 (ui.fan_power)
#define ui_FanRPM2 (ui.fan_rpm)
#define ui_TouchOverlay2 (ui.touch_overlay)
#define ui_FanPowerArc2 (ui.fan_power_arc)

NevermoreDisplayUI nevermore_ui_screen_circle_240_no_plot() {
    lv_obj_t* ui_Container1;
    lv_obj_t* ui_Container2;
    lv_obj_t* ui_Container3;
    lv_obj_t* ui_Label4;
    lv_obj_t* ui_Label5;
    lv_obj_t* ui_Label7;
    lv_obj_t* ui_Label8;
    lv_obj_t* ui_PressureLabels2;
    lv_obj_t* ui_HumidityLabels2;
    lv_obj_t* ui_VocLabels2;
    lv_obj_t* ui_TempLabels2;
    lv_obj_t* ui_FanBox2;
    lv_obj_t* ui_FanLabels2;
    lv_obj_t* ui_FanPowerText2;
    lv_obj_t* ui_FanRpmText2;
    lv_obj_t* ui_FanValuesBox2;

    NevermoreDisplayUI ui = {0};

    ui_no_plot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_no_plot, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_no_plot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_no_plot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_no_plot);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(85));
    lv_obj_set_height(ui_Container1, lv_pct(60));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, lv_pct(2));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(50));
    lv_obj_set_height(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocLabels2 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_VocLabels2);
    lv_obj_set_width(ui_VocLabels2, lv_pct(100));
    lv_obj_set_height(ui_VocLabels2, LV_SIZE_CONTENT);  /// 109
    lv_obj_set_flex_flow(ui_VocLabels2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VocLabels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VocLabels2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label5 = lv_label_create(ui_VocLabels2);
    lv_obj_set_width(ui_Label5, lv_pct(100));
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label5, -10);
    lv_obj_set_y(ui_Label5, -27);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "VOC Index");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocIn2 = lv_label_create(ui_VocLabels2);
    lv_obj_set_width(ui_VocIn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocIn2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_y(ui_VocIn2, 4);
    lv_obj_set_x(ui_VocIn2, lv_pct(45));
    lv_obj_set_align(ui_VocIn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocIn2, "---");
    lv_obj_set_style_text_color(ui_VocIn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocIn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocOut2 = lv_label_create(ui_VocLabels2);
    lv_obj_set_width(ui_VocOut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocOut2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_VocOut2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocOut2, "---");
    lv_obj_set_style_text_color(ui_VocOut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocOut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabels2 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_HumidityLabels2);
    lv_obj_set_width(ui_HumidityLabels2, lv_pct(100));
    lv_obj_set_height(ui_HumidityLabels2, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_align(ui_HumidityLabels2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_HumidityLabels2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HumidityLabels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HumidityLabels2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label8 = lv_label_create(ui_HumidityLabels2);
    lv_obj_set_width(ui_Label8, lv_pct(100));
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Humidity");
    lv_label_set_recolor(ui_Label8, "true");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityIn2 = lv_label_create(ui_HumidityLabels2);
    lv_obj_set_width(ui_HumidityIn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityIn2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_HumidityIn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityIn2, "--- %");
    lv_obj_set_style_text_color(ui_HumidityIn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityIn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityOut2 = lv_label_create(ui_HumidityLabels2);
    lv_obj_set_width(ui_HumidityOut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityOut2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_HumidityOut2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityOut2, "--- %");
    lv_obj_set_style_text_color(ui_HumidityOut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityOut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(50));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(
            ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabels2 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_TempLabels2);
    lv_obj_set_width(ui_TempLabels2, lv_pct(100));
    lv_obj_set_height(ui_TempLabels2, LV_SIZE_CONTENT);  /// 109
    lv_obj_set_flex_flow(ui_TempLabels2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TempLabels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TempLabels2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label4 = lv_label_create(ui_TempLabels2);
    lv_obj_set_width(ui_Label4, lv_pct(100));
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label4, -22);
    lv_obj_set_y(ui_Label4, -3);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temperature");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempIn2 = lv_label_create(ui_TempLabels2);
    lv_obj_set_width(ui_TempIn2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_TempIn2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_TempIn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempIn2, "--- c");
    lv_obj_set_style_text_color(ui_TempIn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempIn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempOut2 = lv_label_create(ui_TempLabels2);
    lv_obj_set_width(ui_TempOut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempOut2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TempOut2, lv_pct(376));
    lv_obj_set_y(ui_TempOut2, lv_pct(-167));
    lv_obj_set_align(ui_TempOut2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempOut2, "--- c");
    lv_obj_set_style_text_color(ui_TempOut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempOut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureLabels2 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_PressureLabels2);
    lv_obj_set_width(ui_PressureLabels2, lv_pct(100));
    lv_obj_set_height(ui_PressureLabels2, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_align(ui_PressureLabels2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_PressureLabels2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_PressureLabels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PressureLabels2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label7 = lv_label_create(ui_PressureLabels2);
    lv_obj_set_width(ui_Label7, lv_pct(100));
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label7, -3);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Pressure");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureIn2 = lv_label_create(ui_PressureLabels2);
    lv_obj_set_width(ui_PressureIn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureIn2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_PressureIn2, 8);
    lv_obj_set_y(ui_PressureIn2, 0);
    lv_obj_set_align(ui_PressureIn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureIn2, "--- hPa");
    lv_obj_set_style_text_color(ui_PressureIn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureIn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureOut2 = lv_label_create(ui_PressureLabels2);
    lv_obj_set_width(ui_PressureOut2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureOut2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_PressureOut2, 16);
    lv_obj_set_y(ui_PressureOut2, -1);
    lv_obj_set_align(ui_PressureOut2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureOut2, "--- hPa");
    lv_obj_set_style_text_color(ui_PressureOut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureOut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PressureOut2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanBox2 = lv_obj_create(ui_no_plot);
    lv_obj_remove_style_all(ui_FanBox2);
    lv_obj_set_width(ui_FanBox2, lv_pct(35));
    lv_obj_set_height(ui_FanBox2, LV_SIZE_CONTENT);  /// 13
    lv_obj_set_x(ui_FanBox2, 0);
    lv_obj_set_y(ui_FanBox2, lv_pct(-2));
    lv_obj_set_align(ui_FanBox2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_FanBox2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FanBox2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FanBox2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanLabels2 = lv_obj_create(ui_FanBox2);
    lv_obj_remove_style_all(ui_FanLabels2);
    lv_obj_set_width(ui_FanLabels2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_FanLabels2, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_x(ui_FanLabels2, 1);
    lv_obj_set_y(ui_FanLabels2, lv_pct(-5));
    lv_obj_set_align(ui_FanLabels2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FanLabels2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FanLabels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FanLabels2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_text_color(ui_FanLabels2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanLabels2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanPowerText2 = lv_label_create(ui_FanLabels2);
    lv_obj_set_width(ui_FanPowerText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPowerText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanPowerText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanPowerText2, "Fan:");
    lv_obj_set_style_text_color(ui_FanPowerText2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanPowerText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanRpmText2 = lv_label_create(ui_FanLabels2);
    lv_obj_set_width(ui_FanRpmText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanRpmText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanRpmText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanRpmText2, "RPM:");
    lv_obj_set_style_text_color(ui_FanRpmText2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanRpmText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanValuesBox2 = lv_obj_create(ui_FanBox2);
    lv_obj_remove_style_all(ui_FanValuesBox2);
    lv_obj_set_height(ui_FanValuesBox2, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_flex_grow(ui_FanValuesBox2, 1);
    lv_obj_set_x(ui_FanValuesBox2, 1);
    lv_obj_set_y(ui_FanValuesBox2, lv_pct(-5));
    lv_obj_set_align(ui_FanValuesBox2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FanValuesBox2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FanValuesBox2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_FanValuesBox2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanPower2 = lv_label_create(ui_FanValuesBox2);
    lv_obj_set_width(ui_FanPower2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPower2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanPower2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanPower2, "0%");
    lv_obj_set_style_text_color(ui_FanPower2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanPower2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanRPM2 = lv_label_create(ui_FanValuesBox2);
    lv_obj_set_width(ui_FanRPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanRPM2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanRPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanRPM2, "0");
    lv_obj_set_style_text_color(ui_FanRPM2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanRPM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchOverlay2 = lv_obj_create(ui_no_plot);
    lv_obj_remove_style_all(ui_TouchOverlay2);
    lv_obj_set_width(ui_TouchOverlay2, lv_pct(100));
    lv_obj_set_height(ui_TouchOverlay2, lv_pct(100));
    lv_obj_set_align(ui_TouchOverlay2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TouchOverlay2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanPowerArc2 = lv_arc_create(ui_no_plot);
    lv_obj_set_width(ui_FanPowerArc2, lv_pct(100));
    lv_obj_set_height(ui_FanPowerArc2, lv_pct(100));
    lv_obj_set_align(ui_FanPowerArc2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanPowerArc2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_set_scroll_dir(ui_FanPowerArc2, LV_DIR_TOP);
    lv_arc_set_range(ui_FanPowerArc2, 0, 200);
    lv_arc_set_bg_angles(ui_FanPowerArc2, 115, 65);
    lv_obj_set_style_arc_width(ui_FanPowerArc2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_FanPowerArc2, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FanPowerArc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FanPowerArc2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_FanPowerArc2, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_FanPowerArc2, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_FanPowerArc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanPowerArc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanPowerArc2, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_FanPowerArc2, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    return ui;
}
