// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: circle-240

#include "ui/common.h"

#define ui_small_plot (ui.screen)
#define ui_TempIn1 (ui.temp_in)
#define ui_TempOut1 (ui.temp_out)
#define ui_HumidityIn1 (ui.humidity_in)
#define ui_HumidityOut1 (ui.humidity_out)
#define ui_PressureIn1 (ui.pressure_in)
#define ui_PressureOut1 (ui.pressure_out)
#define ui_VocIn1 (ui.voc_in)
#define ui_VocOut1 (ui.voc_out)
#define ui_Chart1 (ui.chart)
#define ui_XAxisScale1 (ui.chart_x_axis_scale)
#define ui_FanPower1 (ui.fan_power)
#define ui_FanRPM1 (ui.fan_rpm)
#define ui_TouchOverlay1 (ui.touch_overlay)
#define ui_FanPowerArc1 (ui.fan_power_arc)

NevermoreDisplayUI nevermore_ui_screen_circle_240_small_plot() {
    lv_obj_t* ui_Label1;
    lv_obj_t* ui_Label2;
    lv_obj_t* ui_Label3;
    lv_obj_t* ui_Label6;
    lv_obj_t* ui_Text1;
    lv_obj_t* ui_Text2;
    lv_obj_t* ui_Text3;
    lv_obj_t* ui_Text4;
    lv_obj_t* ui_In;
    lv_obj_t* ui_In1;
    lv_obj_t* ui_In2;
    lv_obj_t* ui_In3;
    lv_obj_t* ui_Out;
    lv_obj_t* ui_Out1;
    lv_obj_t* ui_Out2;
    lv_obj_t* ui_Out3;
    lv_obj_t* ui_ChartBox1;
    lv_obj_t* ui_ChartOverlay1;
    lv_obj_t* ui_PressureLabels1;
    lv_obj_t* ui_HumidityLabels1;
    lv_obj_t* ui_VocLabels1;
    lv_obj_t* ui_TempLabels1;
    lv_obj_t* ui_FanBox1;
    lv_obj_t* ui_FanLabels1;
    lv_obj_t* ui_FanPowerText1;
    lv_obj_t* ui_FanRpmText1;
    lv_obj_t* ui_FanValuesBox1;

    NevermoreDisplayUI ui = {0};

    ui_small_plot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_small_plot, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_small_plot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_small_plot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabels1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_TempLabels1);
    lv_obj_set_width(ui_TempLabels1, lv_pct(24));
    lv_obj_set_height(ui_TempLabels1, LV_SIZE_CONTENT);  /// 109
    lv_obj_set_x(ui_TempLabels1, 85);
    lv_obj_set_y(ui_TempLabels1, 0);
    lv_obj_set_align(ui_TempLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempLabels1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TempLabels1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TempLabels1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label3 = lv_label_create(ui_TempLabels1);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label3, -22);
    lv_obj_set_y(ui_Label3, -3);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Temp");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempIn1 = lv_label_create(ui_TempLabels1);
    lv_obj_set_width(ui_TempIn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempIn1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_TempIn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempIn1, "--- c");
    lv_obj_set_style_text_color(ui_TempIn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempIn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempIn1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempOut1 = lv_label_create(ui_TempLabels1);
    lv_obj_set_width(ui_TempOut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempOut1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TempOut1, lv_pct(376));
    lv_obj_set_y(ui_TempOut1, lv_pct(-167));
    lv_obj_set_align(ui_TempOut1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempOut1, "--- c");
    lv_obj_set_style_text_color(ui_TempOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempOut1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocLabels1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_VocLabels1);
    lv_obj_set_width(ui_VocLabels1, lv_pct(24));
    lv_obj_set_height(ui_VocLabels1, LV_SIZE_CONTENT);  /// 109
    lv_obj_set_x(ui_VocLabels1, -85);
    lv_obj_set_y(ui_VocLabels1, 0);
    lv_obj_set_align(ui_VocLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VocLabels1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VocLabels1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VocLabels1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label1 = lv_label_create(ui_VocLabels1);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label1, -10);
    lv_obj_set_y(ui_Label1, -27);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "VOC");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocIn1 = lv_label_create(ui_VocLabels1);
    lv_obj_set_width(ui_VocIn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocIn1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_y(ui_VocIn1, 4);
    lv_obj_set_x(ui_VocIn1, lv_pct(45));
    lv_obj_set_align(ui_VocIn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocIn1, "---");
    lv_obj_set_style_text_color(ui_VocIn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocIn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocIn1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocOut1 = lv_label_create(ui_VocLabels1);
    lv_obj_set_width(ui_VocOut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocOut1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_VocOut1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocOut1, "---");
    lv_obj_set_style_text_color(ui_VocOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocOut1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureLabels1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_PressureLabels1);
    lv_obj_set_width(ui_PressureLabels1, lv_pct(35));
    lv_obj_set_height(ui_PressureLabels1, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_PressureLabels1, 55);
    lv_obj_set_y(ui_PressureLabels1, -60);
    lv_obj_set_align(ui_PressureLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PressureLabels1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_PressureLabels1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PressureLabels1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label2 = lv_label_create(ui_PressureLabels1);
    lv_obj_set_width(ui_Label2, lv_pct(100));
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Pressure");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureIn1 = lv_label_create(ui_PressureLabels1);
    lv_obj_set_width(ui_PressureIn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureIn1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_PressureIn1, 8);
    lv_obj_set_y(ui_PressureIn1, 0);
    lv_obj_set_align(ui_PressureIn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureIn1, "--- hPa");
    lv_obj_set_style_text_color(ui_PressureIn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureIn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PressureIn1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PressureIn1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PressureIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PressureIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PressureIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureOut1 = lv_label_create(ui_PressureLabels1);
    lv_obj_set_width(ui_PressureOut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureOut1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_PressureOut1, 16);
    lv_obj_set_y(ui_PressureOut1, -1);
    lv_obj_set_align(ui_PressureOut1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureOut1, "--- hPa");
    lv_obj_set_style_text_color(ui_PressureOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PressureOut1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PressureOut1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PressureOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PressureOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PressureOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabels1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_HumidityLabels1);
    lv_obj_set_width(ui_HumidityLabels1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HumidityLabels1, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_HumidityLabels1, -49);
    lv_obj_set_y(ui_HumidityLabels1, -60);
    lv_obj_set_align(ui_HumidityLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidityLabels1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HumidityLabels1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HumidityLabels1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label6 = lv_label_create(ui_HumidityLabels1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Humidity");
    lv_label_set_recolor(ui_Label6, "true");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityIn1 = lv_label_create(ui_HumidityLabels1);
    lv_obj_set_width(ui_HumidityIn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityIn1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_HumidityIn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityIn1, "--- %");
    lv_obj_set_style_text_color(ui_HumidityIn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityIn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityIn1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityIn1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityIn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityOut1 = lv_label_create(ui_HumidityLabels1);
    lv_obj_set_width(ui_HumidityOut1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityOut1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_HumidityOut1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityOut1, "--- %");
    lv_obj_set_style_text_color(ui_HumidityOut1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityOut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityOut1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityOut1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityOut1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_Text1);
    lv_obj_set_width(ui_Text1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Text1, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_Text1, -70);
    lv_obj_set_y(ui_Text1, -53);
    lv_obj_set_align(ui_Text1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Text1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Text1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Text1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_In = lv_label_create(ui_Text1);
    lv_obj_set_width(ui_In, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_In, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_In, LV_ALIGN_CENTER);
    lv_label_set_text(ui_In, "In");
    lv_label_set_recolor(ui_In, "true");
    lv_obj_set_style_text_color(ui_In, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_In, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out = lv_label_create(ui_Text1);
    lv_obj_set_width(ui_Out, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Out, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out, "Out");
    lv_obj_set_style_text_color(ui_Out, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Out, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Out, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Out, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Out, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text2 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_Text2);
    lv_obj_set_width(ui_Text2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Text2, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_Text2, 26);
    lv_obj_set_y(ui_Text2, -53);
    lv_obj_set_align(ui_Text2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Text2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Text2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Text2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_In1 = lv_label_create(ui_Text2);
    lv_obj_set_width(ui_In1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_In1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_In1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_In1, "In");
    lv_label_set_recolor(ui_In1, "true");
    lv_obj_set_style_text_color(ui_In1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_In1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out1 = lv_label_create(ui_Text2);
    lv_obj_set_width(ui_Out1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Out1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out1, "Out");
    lv_obj_set_style_text_color(ui_Out1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Out1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Out1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Out1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Out1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text4 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_Text4);
    lv_obj_set_width(ui_Text4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Text4, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_Text4, 69);
    lv_obj_set_y(ui_Text4, 7);
    lv_obj_set_align(ui_Text4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Text4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Text4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Text4, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_In3 = lv_label_create(ui_Text4);
    lv_obj_set_width(ui_In3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_In3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_In3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_In3, "In");
    lv_label_set_recolor(ui_In3, "true");
    lv_obj_set_style_text_color(ui_In3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_In3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out3 = lv_label_create(ui_Text4);
    lv_obj_set_width(ui_Out3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Out3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out3, "Out");
    lv_obj_set_style_text_color(ui_Out3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Out3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Out3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Out3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Out3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text3 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_Text3);
    lv_obj_set_width(ui_Text3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Text3, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_x(ui_Text3, -101);
    lv_obj_set_y(ui_Text3, 7);
    lv_obj_set_align(ui_Text3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Text3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Text3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Text3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_In2 = lv_label_create(ui_Text3);
    lv_obj_set_width(ui_In2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_In2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_In2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_In2, "In");
    lv_label_set_recolor(ui_In2, "true");
    lv_obj_set_style_text_color(ui_In2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_In2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out2 = lv_label_create(ui_Text3);
    lv_obj_set_width(ui_Out2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Out2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out2, "Out");
    lv_obj_set_style_text_color(ui_Out2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Out2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Out2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Out2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Out2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartBox1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_ChartBox1);
    lv_obj_set_width(ui_ChartBox1, lv_pct(40));
    lv_obj_set_height(ui_ChartBox1, lv_pct(40));
    lv_obj_set_x(ui_ChartBox1, 2);
    lv_obj_set_y(ui_ChartBox1, lv_pct(9));
    lv_obj_set_align(ui_ChartBox1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChartBox1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ChartBox1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ChartBox1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_ChartOverlay1 = lv_obj_create(ui_ChartBox1);
    lv_obj_remove_style_all(ui_ChartOverlay1);
    lv_obj_set_width(ui_ChartOverlay1, lv_pct(100));
    lv_obj_set_flex_grow(ui_ChartOverlay1, 1);
    lv_obj_set_align(ui_ChartOverlay1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ChartOverlay1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Chart1 = lv_chart_create(ui_ChartOverlay1);
    lv_obj_set_width(ui_Chart1, lv_pct(100));
    lv_obj_set_height(ui_Chart1, lv_pct(100));
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 500);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 90);
    lv_chart_set_div_line_count(ui_Chart1, 10, 10);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 8, 5, 10, 2, false, 35);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 5, 3, 0, 2, false, 25);
    lv_obj_set_style_radius(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_XAxisScale1 = lv_label_create(ui_ChartBox1);
    lv_obj_set_width(ui_XAxisScale1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XAxisScale1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_XAxisScale1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_XAxisScale1, "1h");

    ui_FanBox1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_FanBox1);
    lv_obj_set_width(ui_FanBox1, lv_pct(35));
    lv_obj_set_height(ui_FanBox1, LV_SIZE_CONTENT);  /// 13
    lv_obj_set_x(ui_FanBox1, 0);
    lv_obj_set_y(ui_FanBox1, lv_pct(-2));
    lv_obj_set_align(ui_FanBox1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_FanBox1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FanBox1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FanBox1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanLabels1 = lv_obj_create(ui_FanBox1);
    lv_obj_remove_style_all(ui_FanLabels1);
    lv_obj_set_width(ui_FanLabels1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_FanLabels1, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_x(ui_FanLabels1, 1);
    lv_obj_set_y(ui_FanLabels1, lv_pct(-5));
    lv_obj_set_align(ui_FanLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FanLabels1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FanLabels1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FanLabels1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_text_color(ui_FanLabels1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanLabels1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanPowerText1 = lv_label_create(ui_FanLabels1);
    lv_obj_set_width(ui_FanPowerText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPowerText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanPowerText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanPowerText1, "Fan:");

    ui_FanRpmText1 = lv_label_create(ui_FanLabels1);
    lv_obj_set_width(ui_FanRpmText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanRpmText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanRpmText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanRpmText1, "RPM:");

    ui_FanValuesBox1 = lv_obj_create(ui_FanBox1);
    lv_obj_remove_style_all(ui_FanValuesBox1);
    lv_obj_set_height(ui_FanValuesBox1, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_flex_grow(ui_FanValuesBox1, 1);
    lv_obj_set_x(ui_FanValuesBox1, 1);
    lv_obj_set_y(ui_FanValuesBox1, lv_pct(-5));
    lv_obj_set_align(ui_FanValuesBox1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FanValuesBox1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FanValuesBox1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_FanValuesBox1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanPower1 = lv_label_create(ui_FanValuesBox1);
    lv_obj_set_width(ui_FanPower1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPower1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanPower1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanPower1, "0%");
    lv_obj_set_style_text_color(ui_FanPower1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanPower1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanRPM1 = lv_label_create(ui_FanValuesBox1);
    lv_obj_set_width(ui_FanRPM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanRPM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_FanRPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanRPM1, "0");
    lv_obj_set_style_text_color(ui_FanRPM1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanRPM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TouchOverlay1 = lv_obj_create(ui_small_plot);
    lv_obj_remove_style_all(ui_TouchOverlay1);
    lv_obj_set_width(ui_TouchOverlay1, lv_pct(100));
    lv_obj_set_height(ui_TouchOverlay1, lv_pct(100));
    lv_obj_set_align(ui_TouchOverlay1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TouchOverlay1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_FanPowerArc1 = lv_arc_create(ui_small_plot);
    lv_obj_set_width(ui_FanPowerArc1, lv_pct(100));
    lv_obj_set_height(ui_FanPowerArc1, lv_pct(100));
    lv_obj_set_align(ui_FanPowerArc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanPowerArc1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_set_scroll_dir(ui_FanPowerArc1, LV_DIR_TOP);
    lv_arc_set_range(ui_FanPowerArc1, 0, 200);
    lv_arc_set_bg_angles(ui_FanPowerArc1, 115, 65);
    lv_obj_set_style_arc_width(ui_FanPowerArc1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_FanPowerArc1, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FanPowerArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FanPowerArc1, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_FanPowerArc1, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_FanPowerArc1, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_FanPowerArc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanPowerArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanPowerArc1, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_FanPowerArc1, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    return ui;
}
