// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: nevermore

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart = lv_chart_create(ui_Main);
    lv_obj_set_height(ui_Chart, 100);
    lv_obj_set_width(ui_Chart, lv_pct(60));
    lv_obj_set_x(ui_Chart, 0);
    lv_obj_set_y(ui_Chart, -15);
    lv_obj_set_align(ui_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 0, 500);
    lv_chart_set_range(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 90);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_X, 3, 2, 10, 2, true, 35);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 5, 3, 7, 2, true, 25);
    lv_obj_set_style_radius(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Panel0 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel0, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel0, 0);
    lv_obj_set_y(ui_Panel0, 18);
    lv_obj_set_align(ui_Panel0, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel0, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel0, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel0, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel0, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel0);
    lv_obj_set_width(ui_Panel1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureIn = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_PressureIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureIn, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PressureIn, "??? kPa");
    lv_obj_set_style_text_color(ui_PressureIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PressureIn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PressureIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PressureIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PressureIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityIn = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_HumidityIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityIn, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HumidityIn, "??.?%");
    lv_obj_set_style_text_color(ui_HumidityIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityIn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel0);
    lv_obj_set_width(ui_Panel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureOut = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_PressureOut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureOut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureOut, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PressureOut, "??? kPa");
    lv_obj_set_style_text_color(ui_PressureOut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PressureOut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PressureOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PressureOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PressureOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityOut = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_HumidityOut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityOut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityOut, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HumidityOut, "??.?%");
    lv_obj_set_style_text_color(ui_HumidityOut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityOut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_VocPanel, 160);
    lv_obj_set_height(ui_VocPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VocPanel, 0);
    lv_obj_set_y(ui_VocPanel, -27);
    lv_obj_set_align(ui_VocPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_VocPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VocPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VocPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocBarLine100 = lv_obj_create(ui_VocPanel);
    lv_obj_set_width(ui_VocBarLine100, 2);
    lv_obj_set_height(ui_VocBarLine100, 42);
    lv_obj_set_y(ui_VocBarLine100, 0);
    lv_obj_set_x(ui_VocBarLine100, lv_pct(20));
    lv_obj_set_align(ui_VocBarLine100, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_VocBarLine100, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VocBarLine100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VocBarLine100, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBarLine100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VocBarLine100, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocBars = lv_obj_create(ui_VocPanel);
    lv_obj_set_width(ui_VocBars, lv_pct(100));
    lv_obj_set_height(ui_VocBars, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocBars, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VocBars, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VocBars, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VocBars, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VocBars, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VocBars, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VocBars, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VocBars, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocBarIn = lv_bar_create(ui_VocBars);
    lv_bar_set_range(ui_VocBarIn, 0, 500);
    lv_obj_set_height(ui_VocBarIn, 16);
    lv_obj_set_width(ui_VocBarIn, lv_pct(100));
    lv_obj_set_align(ui_VocBarIn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_VocBarIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VocBarIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBarIn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocBarIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocBarIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocBarIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocBarIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VocBarIn, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VocBarIn, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBarIn, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_VocBarIn, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_VocBarIn, 51, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_VocBarIn, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_VocBarIn, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VocLabelIn = lv_label_create(ui_VocBarIn);
    lv_obj_set_width(ui_VocLabelIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocLabelIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocLabelIn, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_VocLabelIn, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_VocLabelIn, "VOC Intake");
    lv_obj_set_style_text_color(ui_VocLabelIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocLabelIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocLabelIn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocLabelIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocLabelIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocLabelIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocValueIn = lv_label_create(ui_VocBarIn);
    lv_obj_set_width(ui_VocValueIn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocValueIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocValueIn, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VocValueIn, "???/500");
    lv_obj_set_style_text_color(ui_VocValueIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocValueIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocValueIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocValueIn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocValueIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocValueIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocBarOut = lv_bar_create(ui_VocBars);
    lv_bar_set_range(ui_VocBarOut, 0, 500);
    lv_obj_set_height(ui_VocBarOut, 16);
    lv_obj_set_width(ui_VocBarOut, lv_pct(100));
    lv_obj_set_align(ui_VocBarOut, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_VocBarOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VocBarOut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBarOut, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VocBarOut, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VocBarOut, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocBarOut, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_VocBarOut, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_VocBarOut, 51, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_VocBarOut, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_VocBarOut, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VocLabelOut = lv_label_create(ui_VocBarOut);
    lv_obj_set_width(ui_VocLabelOut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocLabelOut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocLabelOut, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_VocLabelOut, "VOC Exhaust");
    lv_obj_set_style_text_color(ui_VocLabelOut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocLabelOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocLabelOut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocLabelOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocLabelOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocLabelOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocValueOut = lv_label_create(ui_VocBarOut);
    lv_obj_set_width(ui_VocValueOut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocValueOut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocValueOut, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VocValueOut, "???/500");
    lv_obj_set_style_text_color(ui_VocValueOut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocValueOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VocValueOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VocValueOut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VocValueOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VocValueOut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
